"""
TechCorp FTE Response Formatters
Channel-specific response formatting and message splitting
"""

import re
from typing import List, Optional
import textwrap

def format_for_channel(
    response: str, 
    channel: str, 
    ticket_id: str, 
    customer_name: str = ""
) -> str:
    """
    Format response for specific channel with proper structure and metadata
    
    Args:
        response: The core response content
        channel: Target channel (email, whatsapp, web_form)
        ticket_id: Support ticket identifier
        customer_name: Customer's first name
        
    Returns:
        str: Formatted response ready for delivery
    """
    # Clean up customer name
    name = customer_name.strip() if customer_name else "there"
    
    if channel.lower() == "email":
        return _format_email(response, name, ticket_id)
    elif channel.lower() == "whatsapp":
        return _format_whatsapp(response)
    elif channel.lower() == "web_form":
        return _format_web_form(response, name, ticket_id)
    else:
        # Default to email format for unknown channels
        return _format_email(response, name, ticket_id)

def _format_email(response: str, name: str, ticket_id: str) -> str:
    """Format response for email channel"""
    # Ensure proper line breaks and structure
    formatted_response = response.strip()
    
    # Add greeting
    greeting = f"Hi {name},"
    
    # Add main content with proper paragraph breaks
    content = formatted_response
    
    # Add closing
    closing = """If you have further questions, simply reply to this email.

Best regards,
TechCorp Support Team
Ticket: {ticket_id}
─────────────────────────
This response was generated by TechCorp AI Support.
Reply 'HUMAN' to reach our team.""".format(ticket_id=ticket_id)
    
    # Combine all parts
    full_response = f"{greeting}\n\n{content}\n\n{closing}"
    
    return full_response

def _format_whatsapp(response: str) -> str:
    """Format response for WhatsApp channel"""
    # Clean and trim response
    clean_response = response.strip()
    
    # Remove any existing greetings or formal closings
    # Remove common email greetings
    clean_response = re.sub(r'^(Hi|Hello|Dear)\s+[^,]+,?\s*', '', clean_response, flags=re.IGNORECASE)
    
    # Remove formal closings
    clean_response = re.sub(r'\n*(Best regards|Sincerely|Thanks|Thank you)[^-\n]*[-\n]*$', '', clean_response, flags=re.IGNORECASE)
    clean_response = re.sub(r'\n*TechCorp Support Team.*$', '', clean_response, flags=re.IGNORECASE)
    
    # Clean up extra whitespace
    clean_response = re.sub(r'\n+', ' ', clean_response).strip()
    
    # Truncate to 280 characters to leave room for the human support message
    max_length = 280
    if len(clean_response) > max_length:
        # Try to truncate at sentence boundary
        sentences = re.split(r'[.!?]+', clean_response)
        truncated = ""
        for sentence in sentences:
            if len(truncated + sentence + ".") <= max_length:
                truncated += sentence + "."
            else:
                break
        
        if not truncated:
            # If no sentence fits, truncate word-wise
            truncated = clean_response[:max_length-3] + "..."
        else:
            truncated = truncated.strip()
        
        clean_response = truncated
    
    # Add human support option
    human_support = "\n\n👤 Reply 'human' for live support"
    
    return clean_response + human_support

def _format_web_form(response: str, name: str, ticket_id: str) -> str:
    """Format response for web form channel"""
    # Clean response
    formatted_response = response.strip()
    
    # Add greeting
    greeting = f"Hi {name},"
    
    # Add main content
    content = formatted_response
    
    # Add closing with ticket info and status page link
    closing = f"— TechCorp Support\nTicket {ticket_id} | status.techcorp.io"
    
    # Combine parts
    full_response = f"{greeting}\n\n{content}\n\n{closing}"
    
    return full_response

def split_for_whatsapp(message: str) -> List[str]:
    """
    Split message for WhatsApp to stay under 1600 characters per message
    Splits at sentence boundaries when possible
    
    Args:
        message: Message to split
        
    Returns:
        List[str]: List of message parts
    """
    max_length = 1600
    
    if len(message) <= max_length:
        return [message]
    
    # Split into sentences
    sentences = re.split(r'([.!?]+)', message)
    
    parts = []
    current_part = ""
    
    for i in range(0, len(sentences), 2):  # Process sentence + punctuation pairs
        if i + 1 < len(sentences):
            sentence = sentences[i] + sentences[i+1]
        else:
            sentence = sentences[i]
        
        sentence = sentence.strip()
        if not sentence:
            continue
        
        # Check if adding this sentence would exceed limit
        if len(current_part + sentence) <= max_length:
            current_part += sentence
        else:
            # Save current part if not empty
            if current_part:
                parts.append(current_part.strip())
            
            # Start new part
            current_part = sentence
            
            # If single sentence is too long, split it
            if len(sentence) > max_length:
                # Split long sentence at word boundaries
                words = sentence.split()
                temp_part = ""
                for word in words:
                    if len(temp_part + word + " ") <= max_length:
                        temp_part += word + " "
                    else:
                        if temp_part:
                            parts.append(temp_part.strip())
                        temp_part = word + " "
                
                if temp_part:
                    current_part = temp_part
                else:
                    current_part = ""
    
    # Add the last part
    if current_part:
        parts.append(current_part.strip())
    
    # Add part numbers for multi-part messages
    if len(parts) > 1:
        numbered_parts = []
        for i, part in enumerate(parts, 1):
            numbered_parts.append(f"({i}/{len(parts)}) {part}")
        return numbered_parts
    
    return parts

def validate_channel_length(response: str, channel: str) -> tuple[bool, int]:
    """
    Validate response length against channel constraints
    
    Args:
        response: Response to validate
        channel: Target channel
        
    Returns:
        tuple[bool, int]: (is_valid, actual_length)
    """
    length = len(response)
    
    if channel.lower() == "email":
        return length <= 400 * 5, length  # 400 words ~ 2000 chars
    elif channel.lower() == "whatsapp":
        return length <= 300, length
    elif channel.lower() == "web_form":
        return length <= 300 * 5, length  # 300 words ~ 1500 chars
    else:
        return True, length  # No limit for unknown channels

def clean_response_text(text: str) -> str:
    """
    Clean and normalize response text
    
    Args:
        text: Text to clean
        
    Returns:
        str: Cleaned text
    """
    # Remove excessive whitespace
    text = re.sub(r'\s+', ' ', text)
    
    # Clean up common formatting issues
    text = text.replace('..', '.')
    text = text.replace('!!', '!')
    text = text.replace('??', '?')
    
    # Ensure proper spacing after punctuation
    text = re.sub(r'([.!?])([^ \s])', r'\1 \2', text)
    
    # Remove leading/trailing whitespace
    text = text.strip()
    
    return text

def add_emoji_if_appropriate(text: str, channel: str) -> str:
    """
    Add appropriate emoji if channel supports it and context is suitable
    
    Args:
        text: Response text
        channel: Target channel
        
    Returns:
        str: Text with emoji if appropriate
    """
    if channel.lower() != "whatsapp":
        return text
    
    # Only add emoji for positive/helpful responses
    positive_indicators = ["solved", "resolved", "fixed", "completed", "success", "great", "excellent"]
    if any(indicator in text.lower() for indicator in positive_indicators):
        # Add a simple positive emoji at the end
        if not text.strip().endswith(tuple(['👍', '😊', '✅', '🎉'])):
            return text + " ✅"
    
    return text

def format_error_response(error_message: str, channel: str, ticket_id: str = "", customer_name: str = "") -> str:
    """
    Format error response for specific channel
    
    Args:
        error_message: Error message to format
        channel: Target channel
        ticket_id: Support ticket ID
        customer_name: Customer name
        
    Returns:
        str: Formatted error response
    """
    base_error = "I apologize, but I'm having trouble processing your request right now."
    
    if channel.lower() == "email":
        return format_for_channel(
            f"{base_error} {error_message} I've escalated this to our human team for immediate assistance.",
            channel, ticket_id, customer_name
        )
    elif channel.lower() == "whatsapp":
        return format_for_channel(
            f"{base_error} Reply 'human' for immediate help.",
            channel, ticket_id, customer_name
        )
    else:
        return format_for_channel(
            f"{base_error} {error_message}",
            channel, ticket_id, customer_name
        )

def extract_customer_name(name_field: str) -> str:
    """
    Extract and clean customer name from various formats
    
    Args:
        name_field: Raw name field
        
    Returns:
        str: Clean first name
    """
    if not name_field:
        return ""
    
    # Remove extra whitespace and convert to proper case
    name = name_field.strip().title()
    
    # Extract first name only
    parts = name.split()
    if parts:
        return parts[0]
    
    return name

# Utility functions for message processing

def count_words(text: str) -> int:
    """Count words in text, handling various separators"""
    return len(text.split())

def estimate_reading_time(text: str, words_per_minute: int = 200) -> int:
    """Estimate reading time in seconds"""
    word_count = count_words(text)
    minutes = word_count / words_per_minute
    return int(minutes * 60)

def is_urgent_response(response: str) -> bool:
    """Check if response indicates urgency"""
    urgent_keywords = ["urgent", "immediately", "asap", "emergency", "critical", "important"]
    return any(keyword in response.lower() for keyword in urgent_keywords)

def contains_actionable_steps(response: str) -> bool:
    """Check if response contains actionable steps"""
    step_indicators = ["step", "first", "next", "then", "finally", "1.", "2.", "3.", "•", "-"]
    return any(indicator in response.lower() for indicator in step_indicators)
